In [43]:
import pandas as pd
import requests
from config import zwid,gkey
import json
from xml.etree import ElementTree
from json import dumps
from xmljson import badgerfish as bf
from xml.etree.ElementTree import fromstring
import numpy as np
import time

In [49]:
df=df.drop(columns=['Unnamed: 0'])

In [59]:
df

,latitude,longitude,Address,List_Price,beds,baths,sq_ft
0,41.622990,-87.541717,"668 Sibley Blvd Calumet City, IL 60409","$18,900",4.0,2.0,"1,152"
1,41.622990,-87.541717,"668 Sibley Blvd Calumet City, IL 60409","$18,900",4.0,2.0,"1,152"
2,41.636226,-87.708251,"14046 S Grace Ave Robbins, IL 60472","$16,900",2.0,1.0,937
3,41.636226,-87.708251,"14046 S Grace Ave Robbins, IL 60472","$16,900",2.0,1.0,937
4,41.636226,-87.708251,"14046 S Grace Ave Robbins, IL 60472","$16,900",2.0,1.0,937
5,41.636226,-87.708251,"14046 S Grace Ave Robbins, IL 60472","$16,900",2.0,1.0,937
6,41.763367,-87.662704,"1512 W 72nd St Chicago, IL 60636","$8,900",3.0,2.0,"1,056"
7,41.763367,-87.662704,"1512 W 72nd St Chicago, IL 60636","$8,900",3.0,2.0,"1,056"
8,41.476563,-87.695352,"244 Mantua St Park Forest, IL 60466","$42,900",3.0,1.0,"1,169"
9,41.476563,-87.695352,"244 Mantua St Park Forest, IL 60466","$42,900",3.0,1.0,"1,169"
10,41.849839,-87.762975,"5527 W 22nd Pl Cicero, IL 60804","$129,900",4.0,2.0,"3,220"
11,41.849839,-87.762975,"5527 W 22nd Pl Cicero, IL 60804","$129,900",4.0,2.0,"3,220"
12,41.775320,-87.610318,"6547 S Saint Lawrence Ave Chicago, IL 60637","$59,900",4.0,2.0,"2,164"
13,41.775320,-87.610318,"6547 S Saint Lawrence Ave Chicago, IL 60637","$59,900",4.0,2.0,"2,164"
14,41.761133,-87.646385,"7311 S Peoria St Chicago, IL 60621","$9,900",3.0,2.0,"1,804"
15,41.761133,-87.646385,"7311 S Peoria St Chicago, IL 60621","$9,900",3.0,2.0,"1,804"
16,41.769373,-87.672790,"6828 S Winchester Ave Chicago, IL 60636","$7,900",5.0,2.0,882
17,41.769373,-87.672790,"6828 S Winchester Ave Chicago, IL 60636","$7,900",5.0,2.0,882
18,41.685189,-87.653660,"1244 W 115th St Chicago, IL 60643","$42,900",3.0,2.0,"1,054"
19,41.685189,-87.653660,"1244 W 115th St Chicago, IL 60643","$42,900",3.0,2.0,"1,054"
20,41.831632,-87.796070,"3315 Clinton Ave Berwyn, IL 60402","$232,500",4.0,1.0,"1,739"
21,41.774103,-87.679429,"6553 S Bell Ave Chicago, IL 60636","$60,000",3.0,1.0,984
22,41.774103,-87.679429,"6553 S Bell Ave Chicago, IL 60636","$60,000",3.0,1.0,984
23,41.478122,-87.692114,"6 Minocqua Ct Park Forest, IL 60466","$60,000",2.0,1.0,974
24,41.535313,-87.708856,"1442 Kinross St Flossmoor, IL 60422","$359,900",4.0,3.5,"3,351"
25,41.582903,-87.664514,"1928 169th St Hazel Crest, IL 60429","$115,000",3.0,1.5,"1,744"
26,41.935321,-87.824684,"7916 W Metropole St Elmwood Park, IL 60707","$359,900",3.0,2.0,"1,581"
27,42.023202,-87.987438,"76 Forest Ln Elk Grove Village, IL 60007","$200,000",3.0,1.0,"1,171"
28,41.761202,-87.816905,"7135 Sholer Ave Bridgeview, IL 60455","$299,900",4.0,2.0,"2,765"
29,41.567943,-87.534700,"3357 Madison St Lansing, IL 60438","$82,500",4.0,2.0,"1,152"
...,...,...,...,...,...,...,...
13975,41.813266,-87.620933,"4451 S Indiana Ave Apt 2N Chicago, IL 60653","$75,000",2.0,1.5,"1,100"
13976,41.768096,-87.655760,"6918 S Elizabeth St Chicago, IL 60636","$65,000",5.0,2.0,894
13977,41.503151,-87.667337,"572 W 15th Pl Chicago Heights, IL 60411","$68,000",3.0,1.0,660
13978,41.625159,-87.565508,"406 Oglesby Ave Calumet City, IL 60409","$59,900",3.0,2.0,"1,286"
13979,42.012968,-88.164406,"1032 Meadow Ct Streamwood, IL 60107","$220,000",4.0,1.0,986
13980,41.713153,-87.683459,"9914 S Artesian Ave Chicago, IL 60655","$200,000",3.0,1.5,"1,082"
13981,41.690316,-87.699211,"11143 S Troy St Chicago, IL 60655","$244,500",3.0,1.0,1
13982,41.964855,-87.718335,"4600 N Central Park Ave # 2 Chicago, IL 60625","$170,000",2.0,2.0,2
13983,41.798017,-87.902525,"5015 Woodland Ave Western Springs, IL 60558","$2,099,000",6.0,7.0,"7,500"
13984,41.989069,-87.655777,"5858 N Sheridan Rd Apt 801 Chicago, IL 60660","$70,000",1.0,1.0,700
13985,41.628600,-87.601412,"14637 Memorial Dr Dolton, IL 60419","$118,000",3.0,2.0,"1,311"
13986,41.816547,-87.900539,"4030 Lawn Ave Western Springs, IL 60558","$1,299,000",5.0,5.5,"3,400"
13987,41.482343,-87.732759,"22402 Lakeshore Dr Richton Park, IL 60471","$98,500",3.0,2.0,"1,342"
13988,41.733382,-87.634675,"8831 S Eggleston Ave Chicago, IL 60620","$50,000",2.0,1.5,912
13989,41.740706,-87.642463,"8407 S Gilbert Ct Chicago, IL 60620","$68,900",5.0,2.0,"1,302"
13990,41.939242,-87.683640,"2209 W Belmont Ave Chicago, IL 60618","$475,000",2.0,2.0,2
13991,41.766880,-87.568968,"2303 E 70th Pl Chicago, IL 60649","$139,900",2.0,1.5,"1,442"
13992,41.852090,-87.696418,"2822 W Cermak Rd # 1 Chicago, IL 60623","$99,500",3.0,3.0,3
13993,41.614722,-87.613599,"15431 Haney Rd South Holland, IL 60473","$89,900",4.0,1.5,"1,253"
13994,41.658092,-87.751860,"12840 Terrace Ln Crestwood, IL 60445","$140,000",3.0,1.5,"1,550"
13995,41.921272,-87.760623,"2229 N Long Ave Chicago, IL 60639","$130,000",3.0,3.0,3
13996,42.078205,-87.827181,"2749 Langley Cir Glenview, IL 60026","$442,000",3.0,2.5,"1,760"
13997,41.515818,-87.650364,"833 N Highland Dr Chicago Heights, IL 60411","$102,000",3.0,2.0,"1,200"
13998,41.891756,-87.639436,"420 W Grand Ave Apt 1A Chicago, IL 60654","$1,950,000",3.0,2.5,"7,935"
13999,41.944693,-87.819563,"3548 N Overhill Ave Chicago, IL 60634","$185,000",3.0,2.0,936
14000,41.754870,-87.802775,"7508 S Octavia Ave Bridgeview, IL 60455","$349,900",3.0,2.0,"1,176"
14001,41.682230,-87.704990,"3359 W Merrion Ln Merrionette Park, IL 60803","$225,000",3.0,2.0,"1,611"
14002,42.024875,-88.121415,"1634 Winthrop Ln Schaumburg, IL 60193","$749,000",4.0,3.5,"3,000"
14003,41.526155,-87.718640,"47 Sundance Rd Matteson, IL 60443","$228,000",4.0,3.0,"2,614"
14004,41.961474,-87.768146,"4433 N Parkside Ave Chicago, IL 60630","$359,900",5.0,2.0,"1,192"

In [61]:
df.to_csv('market_data_full_clean.csv',index=False)

In [8]:
df = df.rename(columns = {'List_Price ':'Address'})

In [35]:
new_df = df.dropna()

In [41]:
new_df.to_csv('data_fixed_lat_lon.csv', index =False)

In [39]:
new_df = new_df.rename(columns={'List_Price .1':'list_price'})

In [11]:
df['latitude']=np.nan
df['longitude']=np.nan

In [51]:
start=0
end=len(df)

In [13]:
#############ZILLOW API####################
url = 'http://www.zillow.com/webservice/GetSearchResults.htm?zws-id='
for i in range(start,end):
    address = df['Address'][i]
    zipcode = df['Address'][i].split('IL ')[1]
    resp =requests.get(url+zwid+'&address='+ address +'&citystatezip='+f'{zipcode}')
    
    tree = ElementTree.fromstring(resp.content)
    my_json = dumps(bf.data(tree))
    try:
        latitude = my_json.split('latitude')[1].split('$": ')[1].split('}')[0]
        longitude = my_json.split('longitude')[1].split('$": ')[1].split('}')[0]
    
        df['latitude'][i]=latitude
        df['longitude'][i]=longitude
    except:
        df['latitude'][i]=np.nan
        df['longitude'][i]=np.nan

/Users/stevenorn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/stevenorn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/stevenorn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/stevenorn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [54]:
##########GOOGLE API######################
base_url = 'https://maps.googleapis.com/maps/api/geocode/json?address='

for i in range(start,end):
    if pd.isnull(df['latitude'][i]):
        address = df['Address'][i].replace('#','')
        url = base_url + address + '&key=' + gkey

        response = requests.get(url).json()

        try:
            latitude = response['results'][0]['geometry']['location']['lat']
            longitude = response['results'][0]['geometry']['location']['lng']

            df['latitude'][i]=latitude
            df['longitude'][i]=longitude
        except:
            df['latitude'][i]=np.nan
            df['longitude'][i]=np.nan

/Users/stevenorn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Users/stevenorn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/stevenorn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/stevenorn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [25]:
df.to_csv('cook_county_on_market_with_lat_lon.csv',index=False)

In [24]:
df.iloc[15500:16000]

,Address,List_Price,Unnamed: 2,latitude,longitude
15500,"602 S Park Blvd Streamwood, IL 60107","$470,000",NaN,42.018806,-88.168226
15501,"2253 Burr Oak Ave North Riverside, IL 60546","$577,500",NaN,41.848597,-87.816673
15502,"2410 Hawthorne Ln Flossmoor, IL 60422","$1,750,000",NaN,41.540588,-87.675173
15503,"2520 W Haddon Ave Chicago, IL 60622","$1,655,000",NaN,41.902303,-87.690349
15504,"10638 S Throop St Chicago, IL 60643","$585,000",NaN,41.700173,-87.655141
15505,"1310 W 107th St Chicago, IL 60643","$215,000",NaN,41.699767,-87.655340
15506,"16937 Cottage Grove Ave South Holland, IL 60473","$570,000",NaN,41.587305,-87.596451
15507,"410 Periwinkle Way Prospect Heights, IL 60070","$479,000",NaN,42.119583,-87.949763
15508,"1248 S Federal St Unit D Chicago, IL 60605","$235,000",NaN,NaN,NaN
15509,"3706 N Francisco Ave Chicago, IL 60618","$231,000",NaN,41.948759,-87.700910
15510,"1537 W Rue James Pl Palatine, IL 60067","$305,000",NaN,42.082530,-88.080817
15511,"4258 W 21st St Chicago, IL 60623","$315,000",NaN,41.853588,-87.731950
15512,"1443 W Wrightwood Ave # A Chicago, IL 60614","$187,500",NaN,NaN,NaN
15513,77 S Evergreen Ave Unit 1201 Arlington Heights...,"$138,000",NaN,42.082014,-87.981174
15514,"1331 Pfingsten Rd Northbrook, IL 60062","$297,500",NaN,42.128686,-87.847970
15515,"1341 Pfingsten Rd Northbrook, IL 60062","$323,000",NaN,42.128361,-87.847958
15516,"2924 N Major Ave Chicago, IL 60634","$173,000",NaN,41.933852,-87.769114
15517,"1106 Hickory Dr Western Springs, IL 60558","$900,000",NaN,41.778377,-87.901968
15518,"7557 W 63rd St Summit, IL 60501","$305,000",NaN,NaN,NaN
15519,"3316 Louise Dr Lansing, IL 60438","$3,450,000",NaN,41.552979,-87.536331
15520,"9541 S Commercial Ave Chicago, IL 60617","$54,000",NaN,NaN,NaN
15521,"550 Graceland Ave Apt 8 Des Plaines, IL 60016","$284,000",NaN,42.043514,-87.889605
15522,"537 E Shag Bark Ln Apt H Streamwood, IL 60107","$163,000",NaN,42.035636,-88.164937
15523,"144 S Cuyler Ave Apt 3 Oak Park, IL 60302","$192,000",NaN,NaN,NaN
15524,"1731 N Lorel Ave Chicago, IL 60639","$120,000",NaN,41.912248,-87.759074
15525,"1601 N Courtland Dr Arlington Heights, IL 60004","$9,700",NaN,42.104561,-87.962203
15526,"10652 S Avenue B Chicago, IL 60617","$257,500",NaN,41.701148,-87.526104
15527,"7900 S Drexel Ave Chicago, IL 60619","$96,500",NaN,41.751113,-87.603084
15528,"6758 S Calumet Ave Chicago, IL 60637","$225,000",NaN,41.771276,-87.617295
15529,"3663 Adams St Lansing, IL 60438","$250,000",NaN,41.569868,-87.527167
...,...,...,...,...,...
15970,"406 Oglesby Ave Calumet City, IL 60409","$430,000",NaN,41.625159,-87.565508
15971,"221 N 1st Ave Maywood, IL 60153","$237,000",NaN,41.889764,-87.833961
15972,"117 Forest Edge Dr Palos Park, IL 60464","$167,000",NaN,41.666508,-87.897595
15973,"3804 W 115th Pl Alsip, IL 60803","$318,000",NaN,41.683391,-87.715394
15974,"6640 S Saint Lawrence Ave Chicago, IL 60637","$190,000",NaN,41.773661,-87.611021
15975,"1032 Meadow Ct Streamwood, IL 60107","$269,500",NaN,42.012968,-88.164406
15976,"1238 E 70th St Chicago, IL 60637","$115,000",NaN,41.768122,-87.594368
15977,"2901 E 79th St Chicago, IL 60649","$70,000",10/1/16,NaN,NaN
15978,"9914 S Artesian Ave Chicago, IL 60655","$365,000",9/1/16,41.713153,-87.683459
15979,"6307 26th St Berwyn, IL 60402","$245,000",NaN,NaN,NaN
15980,"6901 S Wentworth Ave Chicago, IL 60621","$262,000",NaN,NaN,NaN
15981,"5504 W Cal Sag Rd Alsip, IL 60803","$160,000",NaN,41.663114,-87.755034
15982,"8048 Crawford Ave Skokie, IL 60076","$175,000",NaN,42.027701,-87.728503
15983,"8624 Lavergne Ave Burbank, IL 60459","$246,000",NaN,41.735305,-87.746096
15984,"11143 S Troy St Chicago, IL 60655","$154,000",NaN,41.690316,-87.699211
15985,"4600 N Central Park Ave # 2 Chicago, IL 60625","$364,000",9/1/16,NaN,NaN
15986,"5811 W 63rd St Chicago, IL 60638","$257,000",8/1/16,41.777700,-87.767127
15987,"2207 183rd St Homewood, IL 60430","$216,000",NaN,41.556899,-87.670357
15988,"5015 Woodland Ave Western Springs, IL 60558","$428,000",NaN,41.798017,-87.902525
15989,"5858 N Sheridan Rd Apt 801 Chicago, IL 60660","$416,000",NaN,41.989069,-87.655777
15990,"14637 Memorial Dr Dolton, IL 60419","$200,000",NaN,41.628600,-87.601412
15991,"406 W 119th St Chicago, IL 60628","$178,000",NaN,41.678190,-87.632651
15992,"329 W 108th St Chicago, IL 60628","$350,000",NaN,41.697687,-87.631601
15993,"4030 Lawn Ave Western Springs, IL 60558","$206,000",8/1/16,41.816547,-87.900539
15994,"2437 W 47th St Chicago, IL 60632","$275,000",7/1/16,NaN,NaN
15995,"22402 Lakeshore Dr Richton Park, IL 60471","$134,000",NaN,41.482343,-87.732759
15996,"10251 Franklin Ave Franklin Park, IL 60131","$620,000",NaN,NaN,NaN
15997,"457 E 87th St Chicago, IL 60619","$790,000",NaN,41.736271,-87.612261
15998,"2758 W 24th St Chicago, IL 60608","$575,000",NaN,NaN,NaN
15999,"8831 S Eggleston Ave Chicago, IL 60620","$251,500",NaN,41.733382,-87.634675